export enum VOICOCommand {
  COMPOSITION_CHECK = 'COMPOSITION_CHECK',
  STUDIO_MODE = 'STUDIO_MODE',
  START_RECORDING = 'START_RECORDING',
  STOP_RECORDING = 'STOP_RECORDING',
  MARK_MISTAKE = 'MARK_MISTAKE',
  SAVE_SESSION = 'SAVE_SESSION',
}
